import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'sv' | 'en' | 'sq';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  sv: {
    // SEO
    'seo.home.title': 'NetvisionKs | Digital Innovation & IT Outsourcing',
    'seo.home.desc': 'NetvisionKs erbjuder skräddarsydd webbutveckling, apputveckling och strategisk HR-outsourcing. Vi kopplar nordiska företag med topptalanger.',
    'seo.about.title': 'Om Oss | Vår Vision & Mission - NetvisionKs',
    'seo.about.desc': 'Vi bygger broar mellan talang och behov. Läs om hur NetvisionKs revolutionerar outsourcing med etiska villkor och högkvalitativ leverans.',
    'seo.services.title': 'Tjänster | Webbutveckling, SEO & Säkerhet',
    'seo.services.desc': 'Helhetslösningar inom IT och marknadsföring. Från cybersäkerhet och dataanalys till modern webbdesign och apputveckling.',
    'seo.contact.title': 'Kontakta Oss | Få en Kostnadsfri Offert',
    'seo.contact.desc': 'Redo att digitalisera din verksamhet? Kontakta NetvisionKs idag för rådgivning eller offert på ditt nästa projekt.',

    // Navbar
    'nav.home': 'HEM',
    'nav.about': 'OM OSS',
    'nav.services': 'TJÄNSTER',
    'nav.news': 'NYHETER',
    'nav.blog': 'BLOGG',
    'nav.faq': 'FAQ',
    'nav.contact': 'KONTAKT',
    'nav.careers': 'JOBBA HOS OSS',
    'nav.quote': 'OFFERT',
    'nav.request_quote': 'BEGÄR OFFERT',
    'nav.open': 'Öppet: Mån-Fre 08-18',

    // Hero - UPDATED
    'hero.subtitle': 'KREATIV & INNOVATIV',
    'hero.title_1': 'DIN',
    'hero.title_2': 'DIGITALA',
    'hero.title_3': 'PARTNER',
    'hero.btn_quote': 'Få Offert',
    'hero.btn_contact': 'Kontakta Oss',

    // Video/Feature Sections
    'feat.1.subtitle': 'GRÄNSLÖS POTENTIAL',
    'feat.1.title': 'GLOBAL UPPKOPLING',
    'feat.1.desc': 'I en alltmer sammankopplad värld raderar vi geografiska barriärer för att föra samman visionära företag med exceptionell talang. Genom att utnyttja spetskompetens från Kosovo – Europas snabbast växande IT-region – ger vi din verksamhet de muskler som krävs för att dominera den globala marknaden. Vår unika modell kombinerar nordisk affärsetik med internationell innovationskraft, vilket skapar en sömlös förlängning av ditt eget team. Upplev kraften i en verkligt global arbetsstyrka där kvalitet, skalbarhet och personligt engagemang står i centrum för varje leverans.',
    'feat.1.btn': 'UPPTÄCK MÖJLIGHETER',

    'feat.2.subtitle': 'FRAMTIDSSÄKRAD',
    'feat.2.title': 'DIGITAL EVOLUTION',
    'feat.2.desc': 'Teknologin står aldrig stilla, och det gör inte vi heller. Vi implementerar morgondagens lösningar redan idag – från avancerad AI-optimering till robust molninfrastruktur – för att säkra din långsiktiga tillväxt. Vårt fokus ligger på att bygga hållbara digitala ekosystem som inte bara löser dagens utmaningar utan också proaktivt möter morgondagens krav. Genom att integrera de senaste framstegen inom maskininlärning och prediktiv analys, förvandlar vi komplex teknologi till kraftfulla affärsverktyg som sänker dina kostnader och ökar din marknadsandel.',
    'feat.2.btn': 'SE VÅR TEKNIK',

    // Services Home
    'services.title': 'VÅRA TJÄNSTER',
    'services.cyber': 'Cybersäkerhet',
    'services.cyber_desc': 'Skydda din digitala infrastruktur med våra avancerade säkerhetslösningar.',
    'services.data': 'Dataanalys',
    'services.data_desc': 'Omvandla data till insikter och driv din affärsutveckling framåt.',
    'services.web': 'Webbutveckling',
    'services.web_desc': 'Skräddarsydda webbplatser som kombinerar prestanda med design.',
    'services.app': 'Apputveckling',
    'services.app_desc': 'Innovativa mobilappar för både iOS och Android plattformar.',
    'services.seo': 'SEO-Optimering',
    'services.seo_desc': 'Maximera din synlighet online och nå rätt målgrupp organiskt.',
    'services.geo': 'GEO Performance',
    'services.geo_desc': 'Generative Engine Optimization för att synas i AI-modeller som ChatGPT.',
    'services.video': 'Video Design',
    'services.video_desc': 'Engagerande rörligt material och motion graphics för digitala kanaler.',
    'services.photo': 'Professionellt Foto',
    'services.photo_desc': 'Högkvalitativ företagsfotografering och produktbilder i världsklass.',
    'services.call_card_title': 'Ring oss för offert',
    'services.call_card_text': 'Redo att starta ditt projekt? Vi finns här för att svara på alla dina frågor.',
    'services.support_title': 'SUPPORT DYGNET RUNT',

    // Projects
    'projects.title': 'PROJEKT VI BYGGT',
    'projects.p1': 'PROJEKTTITEL 1',
    'projects.p2': 'PROJEKTTITEL 2',
    'projects.p3': 'PROJEKTTITEL 3',
    'projects.p4': 'PROJEKTTITEL 4',
    'projects.p5': 'HeltRent.no - Digital Plattform',
    'common.read_more': 'LÄS MER',

    // About Feature
    'about_feat.label': 'OM OSS',
    'about_feat.title': 'FRÅGOR?',
    'about_feat.look_here': 'KOLLA HÄR',
    'about_feat.text': 'Vi hjälper företag att växa genom strategisk HR och digital marknadsföring. Vår expertis sträcker sig över gränserna för att leverera toppresultat.',
    'about_feat.btn': 'HUR FIXAR MAN ETT WEBBFEL?',

    // Pricing
    'pricing.tag_standard': 'PRISVÄRT',
    'pricing.tag_pro': 'POPULÄRAST',
    'pricing.standard_title': 'STANDARD',
    'pricing.pro_title': 'PRO',
    'pricing.btn': 'LÄS MER',
    'pricing.sprint': '2-4 veckors sprint',
    'pricing.monthly': 'Månatligt upplägg',
    'pricing.guarantee': 'NÖJD-KUND-GARANTI',
    'pricing.std_1': 'Snabb design & utveckling',
    'pricing.std_2': 'Dedikerat kreativt team',
    'pricing.std_3': 'Leverans inom 2-3 dagar',
    'pricing.std_4': 'Löpande support',
    'pricing.std_5': 'Skalbar lösning för tillväxt',
    'pricing.pro_1': 'Obegränsade uppgifter (en i taget)',
    'pricing.pro_2': 'Direktkanal i Slack',
    'pricing.pro_3': 'Genomsnittlig leverans 24h',
    'pricing.pro_4': 'Löpande design- & byggsupport',
    'pricing.pro_5': 'Branding och utvecklingssprintar',

    // CTA
    'cta.title': 'Prenumerera på våra nyheter',
    'cta.text': 'Få de senaste insikterna inom HR och digital teknik direkt i inkorgen.',
    'cta.placeholder': 'Din e-postadress',
    'cta.btn': 'SKICKA',

    // Footer
    'footer.desc': 'Vi hjälper företag att växa genom strategisk HR, digital marknadsföring och effektiva outsourcing-lösningar. Din framgång är vårt uppdrag.',
    'footer.contact_title': 'KONTAKTA OSS',
    'footer.address': 'ADRESS',
    'footer.phone': 'TELEFON',
    'footer.email': 'E-POST',
    'footer.hours': 'ÖPPETTIDER',
    'footer.hours_text': 'Helgfria vardagar: 08:00 - 18:00',
    'footer.rights': 'Alla rättigheter förbehållna.',

    // Contact Page
    'contact.label': 'KONTAKTA OSS',
    'contact.title': 'LÅT OSS DISKUTERA DITT',
    'contact.title_2': 'NÄSTA PROJEKT',
    'contact.desc': 'Vi är alltid redo att hjälpa dig. Fyll i formuläret eller kontakta oss via telefon eller e-post för en snabb offert.',
    'contact.visit': 'BESÖK OSS',
    'contact.call': 'RING OSS',
    'contact.mail': 'MAILA OSS',
    'contact.form_name': 'NAMN',
    'contact.form_phone': 'TELEFON',
    'contact.form_email': 'E-POST',
    'contact.form_subject': 'ÄMNE',
    'contact.form_message': 'MEDDELANDE',
    'contact.form_btn': 'SKICKA MEDDELANDE',
    'contact.opt_quote': 'Offertförfrågan',
    'contact.opt_hr': 'HR Support',
    'contact.opt_out': 'Outsourcing',
    'contact.opt_other': 'Övrigt',
    'contact.ph_name': 'Ditt namn',
    'contact.ph_msg': 'Berätta mer om ditt behov...',

    // About Page
    'about.label': 'OM NETVISION KS',
    'about.title_1': 'VI BYGGER BROAR MELLAN',
    'about.title_2': 'TALANG OCH BEHOV',
    'about.intro': 'Netvision KS grundades med en enda, kraftfull idé: att låsa upp den enorma, outnyttjade potentialen hos högutbildade talanger i Kosovo och koppla dem direkt till den globala arbetsmarknaden.',
    'about.mission_title': 'VÅR MISSION',
    'about.mission_p1': 'Vi såg problemet: En stor pool av skickliga, drivna individer inom områden som arkitektur, grafisk design, fotografi, fullstack-utveckling, frontend och backend som kämpade för att hitta värdiga jobb. Samtidigt såg vi ett växande globalt behov av just dessa experter.',
    'about.mission_bold': 'Därför är vår mission tvåfaldig:',
    'about.mission_li1': 'Att erbjuda en värdig lön och en stabil arbetsplats åt Kosovos mest begåvade akademiker.',
    'about.mission_li2': 'Att vara den pålitliga partnern som förser företag globalt med högpresterande remote-team och konsulter för deras projekt.',
    'about.mission_p2': 'Vi löser era problem med spetskompetens, samtidigt som vi löser talangernas problem med arbetsmöjligheter. Vår flexibla modell gör oss till den perfekta partnern för alla företag – oavsett storlek eller bransch – som behöver exceptionell digital talang.',
    'about.values_title': 'HUR VI JOBBAR',
    'about.values_intro': 'Vi är övertygade om att de bästa resultaten uppnås genom förtroende, frihet och en ärlig affärsetik.',
    'about.val1_title': 'ÄRLIGA MÖJLIGHETER',
    'about.val1_desc': 'Alla våra talanger får en ärlig chans till en konkurrenskraftig och värdig lön, samt en arbetsmiljö i toppklass.',
    'about.val2_title': 'FRIHET UNDER ANSVAR',
    'about.val2_desc': 'Vi tror på moderna arbetsstrukturer. Våra team möter sina deadlines och levererar utlovad kvalitet, men har friheten att själva bestämma när och var de jobbar ifrån.',
    'about.val2_quote': '"Världen har aldrig varit så lokal som den är nu."',
    'about.val3_title': 'SKRÄDDARSYDD REKRYTERING',
    'about.val3_desc': 'Vi handplockar och anställer de skarpaste profilerna. Beroende på ert behov kan vi antingen hyra ut hela team eller individuella specialister, eller fakturera för specifika projekt.',
    'about.founders_title': 'MÖT GRUNDARNA',
    'about.founders_desc': 'Deras personliga engagemang säkerställer att varje projekt inte bara levererar kvalitet, utan också uppfyller företagets etiska mål.',
    'about.founder_ceo': 'GRUNDARE & VD',
    'about.founder': 'GRUNDARE',
    'about.founder_bujar_bio': 'Bujar är drivkraften bakom NetvisionKs vision att revolutionera hur företag nyttjar global talang. Med en bakgrund inom strategiskt hantverk och teknik, brinner han för att skapa hållbara arbetsmöjligheter i Kosovo.',
    'about.founder_samet_bio': 'Som medgrundare fokuserar Samet på operativ excellens och att bygga tekniska team i världsklass. Hans förmåga att identifiera spetskompetens är avgörande för NetvisionKs framgång i att leverera komplexa projekt.',
    'about.team_title': 'VÅRT TEAM',
    'about.team_desc': 'Möt människorna som gör magin möjlig. Vi är en mångsidig grupp av kreatörer, utvecklare och strateger.',
    'about.vision_title': 'VÅR VISION',
    'about.vision_quote': '"Vår vision är att Netvision KS ska bli synonymt med kvalitet, pålitlighet och etisk rekrytering från Sydöstra Europa."',
    'about.vision_text': 'Vi strävar efter att vara ledande inom outsourced remote-tjänster och fortsätta bevisa att gränsöverskridande samarbete inte bara är möjligt, utan också den smartaste vägen framåt för både talanger och uppdragsgivare.',

    // Services Page
    'srv_page.title': 'VÅRA TJÄNSTER',
    'srv_page.intro': 'Vi erbjuder omfattande lösningar för moderna företag. Från rekrytering till teknisk utveckling och visuell kommunikation.',
    'srv_page.t1': 'REMOTE OUTSOURCING',
    'srv_page.d1': 'Vår kärnverksamhet handlar om att koppla ihop rätt talang med rätt företag. Vi hanterar hela processen från rekrytering till onboarding och daglig ledning.',
    'srv_page.t2': 'DIGITAL MARKNADSFÖRING',
    'srv_page.d2': 'Vi håller dig uppdaterad med de senaste trenderna och ser till att ditt varumärke syns. Våra nyhetsbrev och marknadsanalyser ger dig ett försprång mot konkurrenterna.',
    'srv_page.t3': 'HR & PERSONAL',
    'srv_page.d3': 'Som HR-specialister förstår vi vikten av företagskultur. Vi hjälper er bygga starka team oavsett om de sitter på kontoret eller arbetar remote.',
    'srv_page.t4': 'GRAFISK DESIGN',
    'srv_page.d4': 'Vi ger ert varumärke liv. Vårt kreativa team skapar allt från logotyper, visitkort, posters och broschyrer till fotorealistiska 3D-animationer och professionell företagsfotografering.',
    'srv_page.tech_title': 'TEKNISKA TJÄNSTER',
    'srv_page.geo_title': 'GEO PERFORMANCE',
    'srv_page.geo_desc': 'I den nya AI-drivna sökepoken räcker det inte med traditionell SEO. Vi optimerar ditt digitala innehåll för att bli en prioriterad källa för Generative AI-motorer som ChatGPT, Perplexity och Google Gemini. Vi säkerställer att din expertis citeras när AI sammanställer svar åt framtida kunder.',
    'srv_page.video_title': 'VIDEO & MOTION DESIGN',
    'srv_page.video_desc': 'Vi producerar högkvalitativt rörligt innehåll som berättar din historia och fångar uppmärksamhet i ett brusigt digitalt landskap. Från dynamiska explainers till avancerad rörelse grafik – vi skapar visuella upplevelser som konverterar besökare till lojala kunder.',
    'srv_page.photo_title': 'PROFESSIONELL FOTOGRAFERING',
    'srv_page.photo_desc': 'Bilder säger mer än tusen ord. Vårt team av professionella fotografer levererar knivskarpa företagsporträtt, produktbilder och stämningsfulla varumärkesbilder som lyfter hela din digitala närvaro till en premium-nivå.',

    // Blog Page
    'blog.subtitle': 'INSIKTER & NYHETER',
    'blog.title': 'VÅR BLOGG',
    'blog.desc': 'Håll dig uppdaterad med de senaste trenderna inom tech, outsourcing och digital innovation.',
    'blog.read_more': 'LÄS MER',
    'blog.not_found': 'Posten hittades inte',
    'blog.back': 'Gå tillbaka till bloggen',
    'blog.reading': 'läsning',
    'blog.like_article': 'Gillade du artikeln?',
    'blog.cta_text': 'Följ oss på sociala medier för fler uppdateringar om tech och digital innovation.',
    'blog.cta_btn': 'Prata med oss',
    'value.back': 'Tillbaka till Om Oss',
    'value.cta_btn': 'Skapa framtiden med oss',
    'value.quote_text': 'Vårt engagemang för detta är grunden i allt vi gör på NetvisionKs.',
    'value.val1_full': 'Vi tror på rättvisa och jämlika möjligheter för alla talanger i regionen. För oss handlar "Ärliga Möjligheter" om att erbjuda löner som inte bara är konkurrenskraftiga lokalt, utan som faktiskt återspeglar den expertis och det värde som levereras till våra globala kunder.',
    'value.val2_full': 'I en digital värld är resultat viktigare än var man sitter. Vi ger våra team full frihet att strukturera sin arbetsdag under förutsättning att vi alltid överträffar kundens förväntningar. Detta skapar en miljö driven av passion snarare än kontroll.',
    'value.val3_full': 'Varje kundbehov är unikt. Därför har vi inget "one-size-fits-all"-tänk. Vi djupdyker i er verksamhet för att förstå exakt vilken kompetensprofil som saknas, och handplockar sedan individer som passar perfekt både tekniskt och kulturellt.',

    // FAQ Page
    'faq.subtitle': 'SUPPORT & INFORMATION',
    'faq.title': 'VANLIGA FRÅGOR',
    'faq.desc': 'Här har vi samlat svar på de vanligaste frågorna om hur vi arbetar, vår process och vad du kan förvänta dig av ett samarbete med oss.',
    'faq.not_found_title': 'Hittade du inte svaret du sökte?',
    'faq.not_found_text': 'Inga problem! Kontakta oss direkt så hjälper vårt team dig med alla funderingar du kan tänkas ha.',
    'faq.contact_btn': 'KONTAKTA OSS',

    // Careers Page
    'careers.subtitle': 'JOBBA HOS OSS',
    'careers.title_prefix': 'BLI EN DEL AV',
    'careers.desc': 'Vi letar alltid efter passionerade talanger som vill vara med och bygga framtidens digitala lösningar. Är du vår nästa stjärna?',
    'careers.benefits_1_title': 'Internationella Projekt',
    'careers.benefits_1_desc': 'Arbeta direkt mot ledande nordiska företag och spännande startups.',
    'careers.benefits_1_full': 'Som anställd på NetvisionKs får du möjlighet att arbeta med stora nordiska varumärken och innovativa startups från dag ett. Du blir en del av ett ekosystem där kvalitet står i centrum och där dina tekniska färdigheter utmanas genom komplexa och givande projekt. Vi arbetar med modern teknikstack och smidiga metoder för att leverera resultat som gör skillnad.',
    'careers.benefits_2_title': 'Karriärutveckling',
    'careers.benefits_2_desc': 'Tydliga karriärvägar, certifieringar och möjlighet att växa i din roll.',
    'careers.benefits_2_full': 'Vi tror på livslångt lärande. Genom NetvisionKs Academy erbjuder vi stöd för internationella certifieringar, interna workshops och en tydlig utvecklingsplan som är skräddarsydd för dina mål. Oavsett om du vill fördjupa dig tekniskt eller ta ett steg mot ledarskap, så ger vi dig de verktyg och det stöd du behöver för att lyckas.',
    'careers.benefits_3_title': 'Balans i Livet',
    'careers.benefits_3_desc': 'Vi värnar om din hälsa med flexibla arbetstider och generösa förmåner.',
    'careers.benefits_3_full': 'Vi förstår att livet händer utanför kontoret. Hos oss är flexibla arbetstider och möjligheten till distansarbete en självklarhet. Vi prioriterar ditt välmående genom hälsoförmåner, regelbundna sociala team-aktiviteter och en kultur som respekterar din personliga tid. En utvilad och balanserad kollega är en kreativ kollega.',
    'careers.benefits_4_title': 'Modern Arbetsmiljö',
    'careers.benefits_4_desc': 'Sitt i våra fräscha lokaler centralt i Prishtina med tillgång till det senaste inom tech.',
    'careers.benefits_4_full': 'Vårt huvudkontor i Prishtina är utformat för samarbete och kreativitet. Med ergonomiska arbetsstationer, avkopplingsytor och den senaste hårdvaran skapar vi en miljö där du kan prestera på topp. Vi främjar en öppen och inkluderande stämning där varje röst räknas och där vi firar våra framgångar tillsammans.',
    'careers.positions_title': 'LEDIGA TJÄNSTER',
    'careers.apply_btn': 'ANSÖK NU',
    'careers.spontaneous_title': 'Hittade du inte rätt roll?',
    'careers.spontaneous_desc': 'Vi växer ständigt och letar alltid efter talanger. Skicka in en spontanansökan så hör vi av oss när en passande möjlighet dyker upp.',
    'careers.response': 'Svar inom 48h',
    'careers.confidentiality': 'Sekretess garanterad',
    'jobs.react_title': 'Senior React Developer',
    'jobs.net_title': 'Fullstack .NET Developer',
    'jobs.hr_title': 'HR Specialist (Nordic Focus)',
    'jobs.type_full': 'Heltid',
    'jobs.loc_remote': 'Prishtina / Remote',
    'jobs.loc_office': 'Prishtina',
    'jobs.react_desc_short': 'Vi söker en senior utvecklare som brinner för frontend, prestanda och användarupplevelse.',
    'jobs.react_desc_full': 'Vi expanderar vårt frontend-team och söker en Senior React Developer som vill ta ansvar för arkitektur och kodkvalitet i våra mest utmanande projekt. Du kommer att arbeta nära våra designers och backend-utvecklare för att skapa blixtsnabba, skalbara webbapplikationer som används av tusentals användare i Norden.',
    'jobs.react_req': 'Minst 5 års erfarenhet av JavaScript/TypeScript;Djup expertis inom React och dess ekosystem (Redux, Zustand, React Query);Erfarenhet av att leda tekniska diskussioner och mentora juniora utvecklare;Starkt fokus på prestandaoptimering och tillgänglighet.',
    'jobs.react_ben': 'Konkurrenskraftig lön;Modern hårdvara;Möjlighet till remote-arbete;Kontinuerlig vidareutbildning.',
    'jobs.net_desc_short': 'Är du expert på C# och moderna molnlösningar? Hjälp våra kunder bygga skalbara system.',
    'jobs.net_desc_full': 'Vi letar efter en Fullstack .NET Developer som trivs i en miljö med högt tempo och teknisk spets. Du kommer att bygga molnbaserade lösningar (Azure/AWS) och säkerställa att våra backend-system är robusta och säkra. Din roll involverar allt från databasdesign till API-utveckling och integrationer.',
    'jobs.net_req': 'Solid erfarenhet av .NET Core och C#;Kunskap om moderna databaser (SQL & NoSQL);Erfarenhet av molnplattformar och CI/CD-pipelines;Förmåga att skriva ren, testbar kod.',
    'jobs.net_ben': 'Certifieringsstöd;Friskvårdsbidrag;Inspirerande kontorsmiljö;Tydlig karriärstege.',
    'jobs.hr_desc_short': 'Vi letar efter dig som förstår både nordisk arbetskultur och den lokala talangmarknaden.',
    'jobs.hr_desc_full': 'Som HR Specialist hos oss spelar du en nyckelroll i att bygga upp våra team i Kosovo. Du fungerar som en länk mellan våra nordiska kunder och våra lokala talanger. Du kommer att ansvara för hela rekryteringsprocessen, från sourcing till onboarding och personalvård.',
    'jobs.hr_req': 'Erfarenhet av tech-rekrytering;Förståelse för nordisk arbetskultur;Utmärkt kommunikationsförmåga på engelska;Drivande och självgående personlighet.',
    'jobs.hr_ben': 'Personlig utveckling;Nätverk med internationella företag;Flexibla arbetstider;En roll med stor påverkan.',
    'careers.send_spontaneous': 'SKICKA SPONTANANSÖKAN',

    'value.bullet1_val1': 'Etisk rekrytering av toppstudenter',
    'value.bullet2_val1': 'Marknadsledande förmåner',
    'value.bullet3_val1': 'Kontinuerlig utbildning och mentorskap',
    'value.bullet4_val1': 'En kultur byggd på respekt och tillit',
    'value.bullet1_val2': 'Resultatfokuserat arbetsflöde',
    'value.bullet2_val2': 'Flexibla arbetstider',
    'value.bullet3_val2': 'Remote-first infrastruktur',
    'value.bullet4_val2': 'Hög kvalitet i varje leverans',
    'value.bullet1_val3': 'Behovsanpassade teamuppställningar',
    'value.bullet2_val3': 'Dedikerade kontonshanterare',
    'value.bullet3_val3': 'Sömlös integration i er organisation',
    'value.bullet4_val3': 'Skalbara lösningar från 1-50 personer',
    'reviews.title': 'VAD VÅRA KUNDER SÄGER',
    'reviews.subtitle': 'Publicerade recensioner',
    'reviews.form_title': 'Lämna din recension',
    'reviews.form_desc': 'Vi värdesätter din feedback för att ständigt förbättra oss.',
    'reviews.label_rating': 'BETYG',
    'reviews.label_name': 'NAMN',
    'reviews.label_comment': 'KOMMENTAR',
    'reviews.btn_submit': 'SKICKA IN',
    'reviews.success_title': 'Tack för din feedback!',
    'reviews.success_desc': 'Ditt meddelande har skickats till vårt team.',
    'cookies.title': 'Vi värnar om din integritet',
    'cookies.desc': 'Vi använder cookies för att förbättra din upplevelse, analysera trafik och personanpassa innehåll. Genom att fortsätta godkänner du vår användning av cookies.',
    'cookies.accept': 'Godkänn alla',
    'cookies.decline': 'Avvisa',
    'cookies.policy': 'Integritetspolicy',
    'cookies.settings': 'Inställningar',
  },
  en: {
    // SEO
    'seo.home.title': 'NetvisionKs | Digital Innovation & IT Outsourcing',
    'seo.home.desc': 'NetvisionKs offers custom web development, app development, and strategic HR outsourcing. Connecting global companies with top talent.',
    'seo.about.title': 'About Us | Our Vision & Mission - NetvisionKs',
    'seo.about.desc': 'We build bridges between talent and needs. Read about how NetvisionKs revolutionizes outsourcing with ethical conditions and high-quality delivery.',
    'seo.services.title': 'Services | Web Development, SEO & Security',
    'seo.services.desc': 'Comprehensive solutions in IT and marketing. From cyber security and data analytics to modern web design and app development.',
    'seo.contact.title': 'Contact Us | Get a Free Quote',
    'seo.contact.desc': 'Ready to digitize your business? Contact NetvisionKs today for advice or a quote on your next project.',

    // Navbar
    'nav.home': 'HOME',
    'nav.about': 'ABOUT US',
    'nav.services': 'SERVICES',
    'nav.news': 'NEWS',
    'nav.blog': 'BLOG',
    'nav.faq': 'FAQ',
    'nav.contact': 'CONTACT',
    'nav.careers': 'CAREERS',
    'nav.quote': 'QUOTE',
    'nav.request_quote': 'REQUEST QUOTE',
    'nav.open': 'Open: Mon-Fri 08-18',

    // Hero - UPDATED
    'hero.subtitle': 'CREATIVE & INNOVATIVE',
    'hero.title_1': 'YOUR',
    'hero.title_2': 'DIGITAL',
    'hero.title_3': 'PARTNER',
    'hero.btn_quote': 'Free Quote',
    'hero.btn_contact': 'Contact Us',

    // Video/Feature Sections
    'feat.1.subtitle': 'LIMITLESS POTENTIAL',
    'feat.1.title': 'GLOBAL CONNECTIVITY',
    'feat.1.desc': 'In an increasingly interconnected world, we erase geographical barriers to bring together visionary companies with exceptional talent. By leveraging top-tier expertise from Kosovo – Europe\'s fastest-growing IT region – we provide your business with the muscle needed to dominate the global market. Our unique model combines Nordic business ethics with international innovation, creating a seamless extension of your own team. Experience the power of a truly global workforce where quality, scalability, and personal commitment are at the center of every delivery.',
    'feat.1.btn': 'DISCOVER OPPORTUNITIES',

    'feat.2.subtitle': 'FUTURE PROOF',
    'feat.2.title': 'DIGITAL EVOLUTION',
    'feat.2.desc': 'Technology never stands still, and neither do we. We implement tomorrow\'s solutions today – from advanced AI optimization to robust cloud infrastructure – to secure your long-term growth. Our focus is on building sustainable digital ecosystems that not only solve today\'s challenges but also proactively meet tomorrow\'s demands. By integrating the latest advancements in machine learning and predictive analytics, we transform complex technology into powerful business tools that lower your costs and increase your market share.',
    'feat.2.btn': 'SEE OUR TECH',

    // Services Home
    'services.title': 'OUR SERVICES',
    'services.cyber': 'Cyber-Security',
    'services.cyber_desc': 'Protect your digital infrastructure with our advanced security solutions.',
    'services.data': 'Data Analytics',
    'services.data_desc': 'Transform data into insights and drive your business development forward.',
    'services.web': 'Web Development',
    'services.web_desc': 'Tailor-made websites that combine performance with design.',
    'services.app': 'Apps Development',
    'services.app_desc': 'Innovative mobile apps for both iOS and Android platforms.',
    'services.seo': 'SEO Optimization',
    'services.seo_desc': 'Maximize your online visibility and reach the right audience organically.',
    'services.geo': 'GEO Performance',
    'services.geo_desc': 'Generative Engine Optimization to appear in AI models like ChatGPT.',
    'services.video': 'Video Design',
    'services.video_desc': 'Engaging video content and motion graphics for digital channels.',
    'services.photo': 'Professional Photo',
    'services.photo_desc': 'World-class corporate photography and high-quality product images.',
    'services.call_card_title': 'Call Us For Quote',
    'services.call_card_text': 'Ready to start your project? We are here to answer all your questions.',
    'services.support_title': '24/7 SUPPORT',

    // Projects
    'projects.title': 'PROJECTS WE HAVE BUILT',
    'projects.p1': 'PROJECT TITLE 1',
    'projects.p2': 'PROJECT TITLE 2',
    'projects.p3': 'PROJECT TITLE 3',
    'projects.p4': 'PROJECT TITLE 4',
    'projects.p5': 'HeltRent.no - Digital Platform',
    'common.read_more': 'READ MORE',

    // About Feature
    'about_feat.label': 'ABOUT US',
    'about_feat.title': 'ANY QUESTIONS?',
    'about_feat.look_here': 'LOOK HERE',
    'about_feat.text': 'We help companies grow through strategic HR and digital marketing. Our expertise crosses borders to deliver top results.',
    'about_feat.btn': 'HOW CAN I FIX A WEBSITE ERROR?',

    // Pricing
    'pricing.tag_standard': 'AFFORDABLE',
    'pricing.tag_pro': 'POPULAR',
    'pricing.standard_title': 'STANDARD',
    'pricing.pro_title': 'PRO',
    'pricing.btn': 'LEARN MORE',
    'pricing.sprint': '2-4 weeks sprint',
    'pricing.monthly': 'Monthly retainer',
    'pricing.guarantee': 'SATISFACTION GUARANTEE',
    'pricing.std_1': 'Fast design & dev',
    'pricing.std_2': 'Dedicated creative team',
    'pricing.std_3': 'Delivery within 2-3 days',
    'pricing.std_4': 'Ongoing support',
    'pricing.std_5': 'Scalable solution for growth',
    'pricing.pro_1': 'Unlimited tasks (one at a time)',
    'pricing.pro_2': 'Direct Slack channel',
    'pricing.pro_3': 'Average delivery 24h',
    'pricing.pro_4': 'Ongoing design & build support',
    'pricing.pro_5': 'Branding and development sprints',

    // CTA
    'cta.title': 'Subscribe to our newsletter',
    'cta.text': 'Get the latest insights in HR and digital technology directly to your inbox.',
    'cta.placeholder': 'Your email address',
    'cta.btn': 'SUBSCRIBE',

    // Footer
    'footer.desc': 'We help companies grow through strategic HR, digital marketing, and effective outsourcing solutions. Your success is our mission.',
    'footer.contact_title': 'CONTACT US',
    'footer.address': 'ADDRESS',
    'footer.phone': 'PHONE',
    'footer.email': 'EMAIL',
    'footer.hours': 'OPENING HOURS',
    'footer.hours_text': 'Weekdays: 08:00 - 18:00',
    'footer.rights': 'All rights reserved.',

    // Contact Page
    'contact.label': 'CONTACT US',
    'contact.title': 'LET\'S DISCUSS YOUR',
    'contact.title_2': 'NEXT PROJECT',
    'contact.desc': 'We are always ready to help you. Fill out the form or contact us via phone or email for a quick quote.',
    'contact.visit': 'VISIT US',
    'contact.call': 'CALL US',
    'contact.mail': 'EMAIL US',
    'contact.form_name': 'NAME',
    'contact.form_phone': 'PHONE',
    'contact.form_email': 'EMAIL',
    'contact.form_subject': 'SUBJECT',
    'contact.form_message': 'MESSAGE',
    'contact.form_btn': 'SEND MESSAGE',
    'contact.opt_quote': 'Request Quote',
    'contact.opt_hr': 'HR Support',
    'contact.opt_out': 'Outsourcing',
    'contact.opt_other': 'Other',
    'contact.ph_name': 'Your name',
    'contact.ph_msg': 'Tell us more about your needs...',

    // About Page
    'about.label': 'ABOUT NETVISION KS',
    'about.title_1': 'WE BUILD BRIDGES BETWEEN',
    'about.title_2': 'TALENT AND NEEDS',
    'about.intro': 'Netvision KS was founded with a single, powerful idea: to unlock the massive, untapped potential of highly educated talents in Kosovo and connect them directly to the global job market.',
    'about.mission_title': 'OUR MISSION',
    'about.mission_p1': 'We saw the problem: A large pool of skilled, driven individuals in fields such as architecture, graphic design, photography, full-stack development, frontend, and backend struggling to find worthy jobs. At the same time, we saw a growing global need for these exact experts.',
    'about.mission_bold': 'Therefore, our mission is twofold:',
    'about.mission_li1': 'To offer a dignified salary and a stable workplace for Kosovo\'s most talented graduates.',
    'about.mission_li2': 'To be the reliable partner that provides global companies with high-performance remote- teams and consultants for their projects.',
    'about.mission_p2': 'We solve your problems with expertise, while solving talents\' problems with job opportunities. Our flexible model makes us the perfect partner for any company – regardless of size or industry – that needs exceptional digital talent.',
    'about.values_title': 'HOW WE WORK',
    'about.values_intro': 'We are convinced that the best results are achieved through trust, freedom, and honest business ethics.',
    'about.val1_title': 'HONEST OPPORTUNITIES',
    'about.val1_desc': 'All our talents get an honest chance at a competitive and dignified salary, as well as a top-class work environment.',
    'about.val2_title': 'FREEDOM WITH RESPONSIBILITY',
    'about.val2_desc': 'We believe in modern work structures. Our teams meet their deadlines and deliver promised quality, but have the freedom to decide when and where they work from.',
    'about.val2_quote': '"The world has never been as local as it is now."',
    'about.val3_title': 'TAILORED RECRUITMENT',
    'about.val3_desc': 'We handpick and hire the sharpest profiles. Depending on your need, we can either rent out entire teams or individual specialists, or bill for specific projects.',
    'about.founders_title': 'MEET THE FOUNDERS',
    'about.founders_desc': 'Their personal commitment ensures that every project not only delivers quality but also meets the company\'s ethical goals.',
    'about.founder_ceo': 'FOUNDER & CEO',
    'about.founder': 'FOUNDER',
    'about.founder_bujar_bio': 'Bujar is the driving force behind NetvisionKs\' vision to revolutionize how companies leverage global talent. With a background in strategic craftsmanship and technology, he is passionate about creating sustainable job opportunities in Kosovo.',
    'about.founder_samet_bio': 'As a co-founder, Samet focuses on operational excellence and building world-class technical teams. His ability to identify top-tier talent is central to NetvisionKs\' success in delivering complex projects.',
    'about.team_title': 'OUR TEAM',
    'about.team_desc': 'Meet the people who make the magic happen. We are a diverse group of creators, developers, and strategists.',
    'about.vision_title': 'OUR VISION',
    'about.vision_quote': '"Our vision is for Netvision KS to become synonymous with quality, reliability, and ethical recruitment from Southeastern Europe."',
    'about.vision_text': 'We strive to be leaders in outsourced remote services and continue to prove that cross-border collaboration is not only possible but also the smartest way forward for both talents and clients.',

    // Services Page
    'srv_page.title': 'OUR SERVICES',
    'srv_page.intro': 'We offer comprehensive solutions for modern businesses. From recruitment to technical development and visual communication.',
    'srv_page.t1': 'REMOTE OUTSOURCING',
    'srv_page.d1': 'Our core business is about connecting the right talent with the right company. We handle the entire process from recruitment to onboarding and daily management.',
    'srv_page.t2': 'DIGITAL MARKETING',
    'srv_page.d2': 'We keep you updated with the latest trends and ensure your brand is seen. Our newsletters and market analyses give you a head start against competitors.',
    'srv_page.t3': 'HR & PERSONNEL',
    'srv_page.d3': 'As HR specialists, we understand the importance of company culture. We help you build strong teams whether they sit in the office or work remotely.',
    'srv_page.t4': 'GRAPHIC DESIGN',
    'srv_page.d4': 'We bring your brand to life. Our creative team creates everything from logos, business cards, posters, and brochures to photorealistic 3D animations and professional corporate photography.',
    'srv_page.tech_title': 'TECHNICAL SERVICES',
    'srv_page.geo_title': 'GEO PERFORMANCE',
    'srv_page.geo_desc': 'In the new AI-driven search era, traditional SEO is no longer enough. We optimize your digital content to become a prioritized source for Generative AI engines like ChatGPT, Perplexity, and Google Gemini. We ensure your expertise is cited when AI compiles answers for future customers.',
    'srv_page.video_title': 'VIDEO & MOTION DESIGN',
    'srv_page.video_desc': 'We produce high-quality moving content that tells your story and captures attention in a noisy digital landscape. From dynamic explainers to advanced motion graphics – we create visual experiences that convert visitors into loyal customers.',
    'srv_page.photo_title': 'PROFESSIONAL PHOTOGRAPHY',
    'srv_page.photo_desc': 'Images speak louder than words. Our team of professional photographers delivers sharp corporate portraits, product images, and atmospheric brand photos that elevate your entire digital presence to a premium level.',

    // Blog Page
    'blog.subtitle': 'INSIGHTS & NEWS',
    'blog.title': 'OUR BLOG',
    'blog.desc': 'Stay updated with the latest trends in tech, outsourcing, and digital innovation.',
    'blog.read_more': 'READ MORE',
    'blog.not_found': 'Post not found',
    'blog.back': 'Back to blog',
    'blog.reading': 'reading',
    'blog.like_article': 'Enjoyed the article?',
    'blog.cta_text': 'Follow us on social media for more updates on tech and digital innovation.',
    'blog.cta_btn': 'Talk to us',
    'value.back': 'Back to About Us',
    'value.cta_btn': 'Shape the future with us',
    'value.quote_text': 'Our commitment to this is the foundation of everything we do at NetvisionKs.',
    'value.val1_full': 'We believe in fairness and equal opportunities for all talents in the region. For us, "Honest Opportunities" means offering salaries that are not only locally competitive but actually reflect the expertise and value delivered to our global clients.',
    'value.val2_full': 'In a digital world, results are more important than physical presence. We give our teams full freedom to structure their workday, provided we always exceed customer expectations. This creates an environment driven by passion rather than control.',
    'value.val3_full': 'Every customer need is unique. Therefore, we have no "one-size-fits-all" mentality. We dive deep into your business to understand exactly which profile is missing and handpick individuals who fit perfectly both technically and culturally.',

    // FAQ Page
    'faq.subtitle': 'SUPPORT & INFORMATION',
    'faq.title': 'FREQUENTLY ASKED QUESTIONS',
    'faq.desc': 'Here we have gathered answers to the most common questions about how we work, our process, and what you can expect from a collaboration with us.',
    'faq.not_found_title': 'Didn\'t find the answer you were looking for?',
    'faq.not_found_text': 'No problem! Contact us directly and our team will help you with any questions you may have.',
    'faq.contact_btn': 'CONTACT US',

    // Careers Page
    'careers.subtitle': 'WORK WITH US',
    'careers.title_prefix': 'BECOME PART OF',
    'careers.desc': 'We are always looking for passionate talents who want to help build the digital solutions of the future. Are you our next star?',
    'careers.benefits_1_title': 'International Projects',
    'careers.benefits_1_desc': 'Work directly with leading Nordic companies and exciting startups.',
    'careers.benefits_2_title': 'Career Development',
    'careers.benefits_2_desc': 'Clear career paths, certifications, and opportunities to grow in your role.',
    'careers.benefits_3_title': 'Work-Life Balance',
    'careers.benefits_3_desc': 'We care about your health with flexible working hours and generous benefits.',
    'careers.benefits_4_title': 'Modern Work Environment',
    'careers.benefits_4_desc': 'Sit in our fresh offices centrally located in Prishtina with access to the latest tech.',
    'careers.positions_title': 'OPEN POSITIONS',
    'careers.apply_btn': 'APPLY NOW',
    'careers.spontaneous_title': 'Didn\'t find the right role?',
    'careers.spontaneous_desc': 'We are constantly growing and always looking for talent. Send in a spontaneous application and we will contact you when a suitable opportunity arises.',
    'careers.response': 'Response within 48h',
    'careers.confidentiality': 'Confidentiality guaranteed',
    'careers.benefits_1_full': 'As an employee at NetvisionKs, you get the opportunity to work with major Nordic brands and innovative startups from day one. You become part of an ecosystem where quality is central and where your technical skills are challenged through complex and rewarding projects. We work with a modern tech stack and agile methods to deliver results that make a difference.',
    'careers.benefits_2_full': 'We believe in lifelong learning. Through NetvisionKs Academy, we offer support for international certifications, internal workshops, and a clear development plan tailored to your goals. Whether you want to deepen your technical expertise or take a step toward leadership, we provide the tools and support you need to succeed.',
    'careers.benefits_3_full': 'We understand that life happens outside the office. With us, flexible working hours and the option for remote work are a given. We prioritize your well-being through health benefits, regular social team activities, and a culture that respects your personal time. A rested and balanced colleague is a creative colleague.',
    'careers.benefits_4_full': 'Our headquarters in Prishtina are designed for collaboration and creativity. With ergonomic workstations, relaxation areas, and the latest hardware, we create an environment where you can perform at your peak. We promote an open and inclusive atmosphere where every voice counts and where we celebrate our successes together.',
    'jobs.react_title': 'Senior React Developer',
    'jobs.net_title': 'Fullstack .NET Developer',
    'jobs.hr_title': 'HR Specialist (Nordic Focus)',
    'jobs.type_full': 'Full-time',
    'jobs.loc_remote': 'Prishtina / Remote',
    'jobs.loc_office': 'Prishtina',
    'jobs.react_desc_short': 'We are looking for a senior developer who is passionate about frontend, performance, and user experience.',
    'jobs.react_desc_full': 'We are expanding our frontend team and are looking for a Senior React Developer who wants to take responsibility for architecture and code quality in our most challenging projects. You will work closely with our designers and backend developers to create lightning-fast, scalable web applications used by thousands of users in the Nordics.',
    'jobs.react_req': 'At least 5 years of experience with JavaScript/TypeScript;Deep expertise in React and its ecosystem (Redux, Zustand, React Query);Experience leading technical discussions and mentoring junior developers;Strong focus on performance optimization and accessibility.',
    'jobs.react_ben': 'Competitive salary;Modern hardware;Remote work options;Continuous training.',
    'jobs.net_desc_short': 'Are you an expert in C# and modern cloud solutions? Help our clients build scalable systems.',
    'jobs.net_desc_full': 'We are looking for a Fullstack .NET Developer who thrives in an environment with high tempo and technical excellence. You will build cloud-based solutions (Azure/AWS) and ensure our backend systems are robust and secure. Your role involves everything from database design to API development and integrations.',
    'jobs.net_req': 'Solid experience in .NET Core and C#;Knowledge of modern databases (SQL & NoSQL);Experience with cloud platforms and CI/CD pipelines;Ability to write clean, testable code.',
    'jobs.net_ben': 'Certification support;Wellness allowance;Inspiring office environment;Clear career path.',
    'jobs.hr_desc_short': 'We are looking for someone who understands both Nordic work culture and the local talent market.',
    'jobs.hr_desc_full': 'As an HR Specialist with us, you play a key role in building our teams in Kosovo. You act as a link between our Nordic clients and our local talents. You will be responsible for the entire recruitment process, from sourcing to onboarding and personnel care.',
    'jobs.hr_req': 'Experience in tech recruitment;Understanding of Nordic work culture;Excellent communication skills in English;Driven and self-motivated personality.',
    'jobs.hr_ben': 'Personal development;Networking with international companies;Flexible working hours;A high-impact role.',
    'careers.send_spontaneous': 'SEND SPONTANEOUS APPLICATION',
    'value.bullet1_val1': 'Ethical recruitment of top students',
    'value.bullet2_val1': 'Market-leading benefits',
    'value.bullet3_val1': 'Continuous training and mentorship',
    'value.bullet4_val1': 'A culture built on respect and trust',
    'value.bullet1_val2': 'Result-focused workflow',
    'value.bullet2_val2': 'Flexible working hours',
    'value.bullet3_val2': 'Remote-first infrastructure',
    'value.bullet4_val2': 'High quality in every delivery',
    'value.bullet1_val3': 'Tailored team setups',
    'value.bullet2_val3': 'Dedicated account managers',
    'value.bullet3_val3': 'Seamless integration into your organization',
    'value.bullet4_val3': 'Scalable solutions from 1-50 people',
    'reviews.title': 'WHAT OUR CLIENTS SAY',
    'reviews.subtitle': 'Published reviews',
    'reviews.form_title': 'Leave your review',
    'reviews.form_desc': 'We value your feedback to constantly improve.',
    'reviews.label_rating': 'RATING',
    'reviews.label_name': 'NAME',
    'reviews.label_comment': 'COMMENT',
    'reviews.btn_submit': 'SUBMIT',
    'reviews.success_title': 'Thanks for your feedback!',
    'reviews.success_desc': 'Your message has been sent to our team.',
    'cookies.title': 'We value your privacy',
    'cookies.desc': 'We use cookies to improve your experience, analyze traffic and personalize content. By continuing, you agree to our use of cookies.',
    'cookies.accept': 'Accept all',
    'cookies.decline': 'Decline',
    'cookies.policy': 'Privacy Policy',
    'cookies.settings': 'Settings',
  },
  sq: {
    // SEO
    'seo.home.title': 'NetvisionKs | Inovacion Digjital & Outsourcing IT',
    'seo.home.desc': 'NetvisionKs ofron zhvillim uebi të personalizuar, zhvillim aplikacionesh dhe outsourcing strategjik të burimeve njerëzore. Ne lidhim kompanitë nordike me talentet më të mira.',
    'seo.about.title': 'Rreth Nesh | Vizioni & Misioni Ynë - NetvisionKs',
    'seo.about.desc': 'Ne ndërtojmë ura midis talentit dhe nevojave. Lexoni sesi NetvisionKs revolucionarizon outsourcing-un me kushte etike dhe shpërndarje të cilësisë së lartë.',
    'seo.services.title': 'Shërbimet | Zhvillim Uebi, SEO & Siguria',
    'seo.services.desc': 'Zgjidhje gjithëpërfshirëse në IT dhe marketing. Nga siguria kibernetike dhe analiza e të dhënave deri tek dizajni modern i uebit dhe zhvillimi i aplikacioneve.',
    'seo.contact.title': 'Na Kontaktoni | Merrni një Ofertë Falas',
    'seo.contact.desc': 'Gati për të digjitalizuar biznesin tuaj? Kontaktoni NetvisionKs sot për këshilla ose një ofertë për projektin tuaj të ardhshëm.',

    // Navbar
    'nav.home': 'KREU',
    'nav.about': 'RRETH NESH',
    'nav.services': 'SHËRBIMET',
    'nav.news': 'LAJME',
    'nav.blog': 'BLOG',
    'nav.faq': 'FAQ',
    'nav.contact': 'KONTAKT',
    'nav.careers': 'KARRIERA',
    'nav.quote': 'OFERTË',
    'nav.request_quote': 'KËRKONI OFERTË',
    'nav.open': 'Hapur: Hën-Pre 08-18',

    // Hero - UPDATED
    'hero.subtitle': 'KREATIV & INOVATIV',
    'hero.title_1': 'PARTNERI',
    'hero.title_2': 'JUAJ',
    'hero.title_3': 'DIGJITAL',
    'hero.btn_quote': 'Merrni Ofertë',
    'hero.btn_contact': 'Na Kontaktoni',

    // Video/Feature Sections
    'feat.1.subtitle': 'POTENCIAL I PAKUFIZUAR',
    'feat.1.title': 'LIDHJE GLOBALE',
    'feat.1.desc': 'Në një botë gjithnjë e më të ndërlidhur, ne fshijmë pengesat gjeografike për të sjellë së bashku kompanitë vizionare me talente të jashtëzakonshme. Duke shfrytëzuar ekspertizën e nivelit të lartë nga Kosova – rajoni i IT-së me rritjen më të shpejtë në Evropë – ne i sigurojmë biznesit tuaj fuqinë e nevojshme për të dominuar tregun global. Modeli ynë unik kombinon etikën e biznesit nordik me inovacionin ndërkombëtar, duke krijuar një zgjatim të pandërprerë të ekipit tuaj. Përjetoni fuqinë e një fuqie punëtore vërtet globale ku cilësia, shkallëzueshmëria dhe angazhimi personal janë në qendër të çdo dërgese.',
    'feat.1.btn': 'ZBULONI MUNDËSITË',

    'feat.2.subtitle': 'SIGURUAR PËR TË ARDHMEN',
    'feat.2.title': 'EVOLUCION DIGJITAL',
    'feat.2.desc': 'Teknologjia nuk ndalet kurrë, dhe as ne. Ne implementojmë zgjidhjet e së nesërmes sot për të siguruar rritjen tuaj.',
    'feat.2.btn': 'SHIHNI TEKNOLOGJINË TONË',

    // Services Home
    'services.title': 'SHËRBIMET TONA',
    'services.cyber': 'Siguria Kibernetike',
    'services.cyber_desc': 'Mbroni infrastrukturën tuaj digjitale me zgjidhjet tona të avancuara të sigurisë.',
    'services.data': 'Analiza e të Dhënave',
    'services.data_desc': 'Transformoni të dhënat në njohuri dhe çoni përpara zhvillimin e biznesit tuaj.',
    'services.web': 'Zhvillim Uebi',
    'services.web_desc': 'Faqe uebi të personalizuara që kombinojnë performancën me dizajnin.',
    'services.app': 'Zhvillim Aplikacionesh',
    'services.app_desc': 'Aplikacione inovative mobile për platformat iOS dhe Android.',
    'services.seo': 'Optimizim SEO',
    'services.seo_desc': 'Maksimizoni dukshmërinë tuaj online dhe arrini audiencën e duhur organikisht.',
    'services.geo': 'GEO Performance',
    'services.geo_desc': 'Optimizimi i Motorit Gjenerativ për t\'u shfaqur në modelet AI si ChatGPT.',
    'services.video': 'Video Design',
    'services.video_desc': 'Përmbajtje vizuale tërheqëse dhe motion graphics për kanalet dixhitale.',
    'services.photo': 'Foto Profesionale',
    'services.photo_desc': 'Fotografi korporative e klasit botëror dhe imazhe cilësore të produkteve.',
    'services.call_card_title': 'Na telefononi për ofertë',
    'services.call_card_text': 'Gati për të filluar projektin tuaj? Ne jemi këtu për t\'iu përgjigjur të gjitha pyetjeve tuaja.',
    'services.support_title': 'MBËSHTETJE 24/7',

    // Projects
    'projects.title': 'PROJEKTE QË KEMI NDËRTUAR',
    'projects.p1': 'TITULLI I PROJEKTIT 1',
    'projects.p2': 'TITULLI I PROJEKTIT 2',
    'projects.p3': 'TITULLI I PROJEKTIT 3',
    'projects.p4': 'TITULLI I PROJEKTIT 4',
    'projects.p5': 'HeltRent.no - Platforma Digjitale',
    'common.read_more': 'LEXO MË SHUMË',

    // About Feature
    'about_feat.label': 'RRETH NESH',
    'about_feat.title': 'KENI PYETJE?',
    'about_feat.look_here': 'SHIKONI KËTU',
    'about_feat.text': 'Ne ndihmojmë kompanitë të rriten përmes HR strategjik dhe marketingut digjital. Ekspertiza jonë kalon kufijtë për të ofruar rezultate maksimale.',
    'about_feat.btn': 'SI TË RREGULLOJ NJË GABIM NË UEB?',

    // Pricing
    'pricing.tag_standard': 'EKONOMIKE',
    'pricing.tag_pro': 'MË POPULLORJA',
    'pricing.standard_title': 'STANDARD',
    'pricing.pro_title': 'PRO',
    'pricing.btn': 'MËSONI MË SHUMË',
    'pricing.sprint': 'Sprint 2-4 javor',
    'pricing.monthly': 'Angazhim mujor',
    'pricing.guarantee': 'GARANCI PËR KËNAQËSI',
    'pricing.std_1': 'Dizajn & zhvillim i shpejtë',
    'pricing.std_2': 'Ekip kreativ i dedikuar',
    'pricing.std_3': 'Dorëzim brenda 2-3 ditësh',
    'pricing.std_4': 'Mbështetje e vazhdueshme',
    'pricing.std_5': 'Zgjidhje e shkallëzueshme për rritje',
    'pricing.pro_1': 'Detyra të pakufizuara (një nga një)',
    'pricing.pro_2': 'Kanal i drejtpërdrejtë në Slack',
    'pricing.pro_3': 'Dorëzim mesatar 24 orë',
    'pricing.pro_4': 'Mbështetje e vazhdueshme për dizajn & ndërtim',
    'pricing.pro_5': 'Sprinte brandimi dhe zhvillimi',

    // CTA
    'cta.title': 'Abonohuni në lajmet tona',
    'cta.text': 'Merrni njohuritë më të fundit në HR dhe teknologji digjitale direkt në kutinë tuaj hyrëse.',
    'cta.placeholder': 'Adresa juaj e emailit',
    'cta.btn': 'ABONOHUNI',

    // Footer
    'footer.desc': 'Ne ndihmojmë kompanitë të rriten përmes HR strategjik, marketingut digjital dhe zgjidhjeve efektive të outsourcing. Suksesi juaj është misioni ynë.',
    'footer.contact_title': 'NA KONTAKTONI',
    'footer.address': 'ADRESA',
    'footer.phone': 'TELEFONI',
    'footer.email': 'EMAIL',
    'footer.hours': 'ORARI I PUNËS',
    'footer.hours_text': 'Hënë - Premte: 08:00 - 18:00',
    'footer.rights': 'Të gjitha të drejtat e rezervuara.',

    // Contact Page
    'contact.label': 'NA KONTAKTONI',
    'contact.title': 'LE TË DISKUTOJMË PROJEKTIN',
    'contact.title_2': 'TUAJ TË ARDHSHËM',
    'contact.desc': 'Ne jemi gjithmonë të gatshëm t\'ju ndihmojmë. Plotësoni formularin ose na kontaktoni përmes telefonit ose emailit për një ofertë të shpejtë.',
    'contact.visit': 'NA VIZITONI',
    'contact.call': 'NA TELEFONONI',
    'contact.mail': 'NA DËRGONI EMAIL',
    'contact.form_name': 'EMRI',
    'contact.form_phone': 'TELEFONI',
    'contact.form_email': 'EMAIL',
    'contact.form_subject': 'SUBJEKTI',
    'contact.form_message': 'MESAZHI',
    'contact.form_btn': 'DËRGO MESAZHIN',
    'contact.opt_quote': 'Kërkesë për Ofertë',
    'contact.opt_hr': 'Mbështetje HR',
    'contact.opt_out': 'Outsourcing',
    'contact.opt_other': 'Tjetër',
    'contact.ph_name': 'Emri juaj',
    'contact.ph_msg': 'Na tregoni më shumë për nevojat tuaja...',

    // About Page
    'about.label': 'RRETH NETVISION KS',
    'about.title_1': 'NE NDËRTOJMË URA MIDIS',
    'about.title_2': 'TALENTIT DHE NEVOJAVE',
    'about.intro': 'Netvision KS u themelua me një ide të vetme dhe të fuqishme: për të zhbllokuar potencialin masiv dhe të pashfrytëzuar të talenteve të arsimuar lart në Kosovë dhe për t\'i lidhur ata drejtpërdrejt me tregun global të punës.',
    'about.mission_title': 'MISIONI YNË',
    'about.mission_p1': 'Ne pamë problemin: Një grup i madh individësh të aftë dhe të motivuar në fusha si arkitektura, dizajni grafik, fotografia, zhvillimi full-stack, frontend dhe backend që luftonin për të gjetur punë të denja. Në të njëjtën kohë, pamë një nevojë globale në rritje për pikërisht këta ekspertë.',
    'about.mission_bold': 'Prandaj, misioni ynë është i dyfishtë:',
    'about.mission_li1': 'Të ofrojmë një pagë të dinjitetshme dhe një vend pune të qëndrueshëm për të diplomuarit më të talentuar të Kosovës.',
    'about.mission_li2': 'Të jemi partneri i besueshëm që u ofron kompanive globale ekipe remote me performancë të lartë dhe konsulentë për projektet e tyre.',
    'about.mission_p2': 'Ne zgjidhim problemet tuaja me ekspertizë, ndërkohë që zgjidhim problemet e talenteve me mundësi punësimi. Modeli ynë fleksibël na bën partnerin e përsosur për çdo kompani – pavarësisht madhësisë apo industrisë – që ka nevojë për talent digjital të jashtëzakonshëm.',
    'about.values_title': 'SI PUNOJMË NE',
    'about.values_intro': 'Ne jemi të bindur se rezultatet më të mira arrihen përmes besimit, lirisë dhe etikës së ndershme të biznesit.',
    'about.val1_title': 'MUNDËSI TË NDERSHME',
    'about.val1_desc': 'Të gjithë talentet tanë marrin një shans të ndershëm për një pagë konkurruese dhe të dinjitetshme, si dhe një mjedis pune të klasit të parë.',
    'about.val2_title': 'LIRI ME PËRGJEGJËSI',
    'about.val2_desc': 'Ne besojmë në strukturat moderne të punës. Ekipet tona respektojnë afatet dhe ofrojnë cilësinë e premtuar, por kanë lirinë të vendosin se kur dhe nga ku punojnë.',
    'about.val2_quote': '"Bota nuk ka qenë kurrë kaq lokale sa është tani."',
    'about.val3_title': 'REKRUTIM I PERSONALIZUAR',
    'about.val3_desc': 'Ne zgjedhim dhe punësojmë profilet më të mprehta. Në varësi të nevojës suaj, ne mund të japim me qira ekipe të tëra ose specialistë individualë, ose të faturojmë për projekte specifike.',
    'about.founders_title': 'NJIHUNI ME THEMELUESIT',
    'about.founders_desc': 'Angazhimi i tyre personal siguron që çdo projekt jo vetëm të ofrojë cilësi, por edhe të përmbushë qëllimet etike të kompanisë.',
    'about.founder_ceo': 'THEMELUES & CEO',
    'about.founder': 'THEMELUES',
    'about.founder_bujar_bio': 'Bujar është forca lëvizëse pas vizionit të NetvisionKs për të revolucionarizuar mënyrën se si kompanitë shfrytëzojnë talentin global. Me një përvojë në strategji dhe teknologji, ai është i apasionuar pas krijimit të mundësive të qëndrueshme të punësimit në Kosovë.',
    'about.founder_samet_bio': 'Si bashkëthemelues, Sameti fokusohet në përsosmërinë operacionale dhe ndërtimin e ekipeve teknike të klasit botëror. Aftësia e tij për të identifikuar talentet kryesore është qendrore për suksesin e NetvisionKs në dërgimin e projekteve komplekse.',
    'about.team_title': 'EKIPY YNË',
    'about.team_desc': 'Njihuni me njerëzit që bëjnë magjinë të mundur. Ne jemi një grup i shumëllojshëm krijuesish, zhvilluesish dhe strategësh.',
    'about.vision_title': 'VIZIONI YNË',
    'about.vision_quote': '"Vizioni ynë është që Netvision KS të bëhet sinonim i cilësisë, besueshmërisë dhe rekrutimit etik nga Evropa Juglindore."',
    'about.vision_text': 'Ne përpiqemi të jemi lider në shërbimet remote të jashtme dhe të vazhdojmë të dëshmojmë se bashkëpunimi ndërkufitar nuk është vetëm i mundur, por edhe rruga më e zgjuar përpara si për talentet ashtu edhe për klientët.',

    // Services Page
    'srv_page.title': 'SHËRBIMET TONA',
    'srv_page.intro': 'Ne ofrojmë zgjidhje gjithëpërfshirëse për bizneset moderne. Nga rekrutimi tek zhvillimi teknik dhe komunikimi vizual.',
    'srv_page.t1': 'OUTSOURCING NË DISTANCË',
    'srv_page.d1': 'Biznesi ynë kryesor ka të bëjë me lidhjen e talentit të duhur me kompaninë e duhur. Ne menaxhojmë të gjithë procesin nga rekrutimi deri te integrimi dhe menaxhimi ditor.',
    'srv_page.t2': 'MARKETING DIGJITAL',
    'srv_page.d2': 'Ne ju mbajmë të përditësuar me trendet më të fundit dhe sigurojmë që marka juaj të shihet. Buletinet tona dhe analizat e tregut ju japin një avantazh ndaj konkurrentëve.',
    'srv_page.t3': 'HR & PERSONEL',
    'srv_page.d3': 'Si specialistë të HR, ne e kuptojmë rëndësinë e kulturës së kompanisë. Ne ju ndihmojmë të ndërtoni ekipe të forta pavarësisht nëse ato janë në zyrë apo punojnë në distancë.',
    'srv_page.t4': 'DIZAJN GRAFIK',
    'srv_page.d4': 'Ne i japim jetë markës suaj. Ekipi ynë kreativ krijon gjithçka nga logot, kartvizitat, posterat dhe broshurat deri te animacionet fotorealiste 3D dhe fotografia profesionale e korporatave.',
    'srv_page.tech_title': 'SHËRBIMET TEKNIKE',
    'srv_page.geo_title': 'GEO PERFORMANCE',
    'srv_page.geo_desc': 'Në epokën e re të kërkimit të drejtuar nga AI, SEO tradicional nuk mjafton më. Ne fëndojmë përmbajtjen tuaj dixhitale për t\'u bërë një burim i priorituar për motorët e AI Gjenerative si ChatGPT, Perplexity dhe Google Gemini. Ne sigurojmë që ekspertiza juaj të citohet kur AI përpilon përgjigje për klientët e ardhshëm.',
    'srv_page.video_title': 'DIZAJN VIDEO & MOTION',
    'srv_page.video_desc': 'Ne prodhojmë përmbajtje vizuale cilësore që tregon historinë tuaj dhe kap vëmendjen në një peizazh dixhital të zhurmshëm. Nga shpjeguesit dinamikë te motion graphics e avancuara – ne krijojmë përvoja vizuale që konvertojnë vizitorët në klientë besnikë.',
    'srv_page.photo_title': 'FOTOGRAFI PROFESIONALE',
    'srv_page.photo_desc': 'Imazhet flasin më shumë se fjalët. Ekipi ynë i fotografëve profesionalë ofron portrete korporative të mprehta, imazhe produktesh dhe foto marke atmosferike që nisin të gjithë praninë tuaj dixhitale në një nivel premium.',

    // Blog Page
    'blog.subtitle': 'VËSHTRIME & LAJME',
    'blog.title': 'BLOGU YNË',
    'blog.desc': 'Qëndroni të përditësuar me trendet e fundit në teknologji, outsourcing dhe inovacion digjital.',
    'blog.read_more': 'LEXO MË SHUMË',
    'blog.not_found': 'Postimi nuk u gjet',
    'blog.back': 'Kthehu te blogu',
    'blog.reading': 'lexim',
    'blog.like_article': 'Ju pëlqeu artikulli?',
    'blog.cta_text': 'Na ndiqni në mediat sociale për më shumë përditësime mbi teknologjinë dhe inovacionin digjital.',
    'blog.cta_btn': 'Bisedoni me ne',
    'value.back': 'Kthehu te Rreth Nesh',
    'value.cta_btn': 'Ndërtoni të ardhmen me ne',
    'value.quote_text': 'Angazhimi ynë për këtë është themeli i gjithçkaje që bëjmë në NetvisionKs.',
    'value.val1_full': 'Ne besojmë në drejtësi dhe mundësi të barabarta për të gjithë talentet në rajon. Për ne, "Mundësitë e Ndershme" nënkuptojnë ofrimin e pagave që nuk janë vetëm konkurruese lokalisht, por në fakt pasqyrojnë ekspertizën och vlerën që u ofrohet klientëve tanë globalë.',
    'value.val2_full': 'Në një botë digjitale, rezultatet janë më të rëndësishme se sa vendi ku uleni. Ne u japim ekipeve tona liri të plotë për të strukturuar ditën e tyre të punës me kusht që të tejkalojmë gjithmonë pritjet e klientëve. Kjo krijon një mjedis të udhëhequr nga pasioni dhe jo kontrolli.',
    'value.val3_full': 'Çdo nevojë e klientit është unike. Prandaj, ne nuk kemi një mendësi "një madhësi i përshtatet të gjithëve". Ne zhytemi thellë në biznesin tuaj për të kuptuar saktësisht se cili profil kompetence mungon och zgjedhim me dorë individët që përshtaten në mënyrë perfekte si teknikisht ashtu edhe kulturalisht.',

    // FAQ Page
    'faq.subtitle': 'MBËSHTETJE & INFORMACION',
    'faq.title': 'PYETJET MË TË SHPESHTA',
    'faq.desc': 'Këtu kemi mbledhur përgjigjet e pyetjeve më të zakonshme se si punojmë, procesin tonë dhe çfarë mund të prisni nga një bashkëpunim me ne.',
    'faq.not_found_title': 'Nuk e gjetët përgjigjen që kërkonit?',
    'faq.not_found_text': 'Asnjë problem! Na kontaktoni direkt dhe ekipi ynë do t\'ju ndihmojë me çdo pyetje që mund të keni.',
    'faq.contact_btn': 'NA KONTAKTONI',

    // Careers Page
    'careers.subtitle': 'PUNONI ME NE',
    'careers.title_prefix': 'BËHU PJESË E',
    'careers.desc': 'Ne gjithmonë kërkojmë talente pasionantë që duan të ndihmojnë në ndërtimin e zgjidhjeve digjitale të së ardhmes. A jeni ju ylli ynë i ardhshëm?',
    'careers.benefits_1_title': 'Projekte Ndërkombëtare',
    'careers.benefits_1_desc': 'Punoni direkt me kompanitë kryesore nordike dhe startup-e emocionuese.',
    'careers.benefits_2_title': 'Zhvillim Karriere',
    'careers.benefits_2_desc': 'Rrugë të qarta karriere, certifikime dhe mundësi për t\'u rritur në rolin tuaj.',
    'careers.benefits_3_title': 'Balanci Punë-Jetë',
    'careers.benefits_3_desc': 'Ne kujdesemi për shëndetin tuaj me orare fleksibël dhe përfitime bujare.',
    'careers.benefits_4_title': 'Mjedis Modern Pune',
    'careers.benefits_4_desc': 'Punoni në zyrat tona të reja në qendër të Prishtinës me akses në teknologjinë më të fundit.',
    'careers.positions_title': 'POZICIONET E HAPURA',
    'careers.apply_btn': 'APLIKONI TANI',
    'careers.spontaneous_title': 'Nuk e gjetët rolin e duhur?',
    'careers.spontaneous_desc': 'Ne po rritemi vazhdimisht dhe gjithmonë kërkojmë talent. Dërgoni një aplikim spontan dhe ne do t\'ju kontaktojmë kur të shfaqet një mundësi e përshtatshme.',
    'careers.response': 'Përgjigje brenda 48 orëve',
    'careers.confidentiality': 'Konfidencialitet i garantuar',
    'jobs.react_title': 'Senior React Developer',
    'jobs.net_title': 'Fullstack .NET Developer',
    'jobs.hr_title': 'Specialist i BNJ (Fokus Nordik)',
    'jobs.type_full': 'Me orar të plotë',
    'jobs.loc_remote': 'Prishtinë / Remote',
    'jobs.loc_office': 'Prishtinë',
    'jobs.react_desc_short': 'Ne po kërkojmë një zhvillues senior që ka pasion frontend-in, performancën dhe përvojën e përdoruesit.',
    'jobs.react_desc_full': 'Ne po zgjerojmë ekipin tonë të frontend-it dhe po kërkojmë një Senior React Developer i cili dëshiron të marrë përgjegjësinë për arkitekturën dhe cilësinë e kodit në projektet tona më sfiduese. Ju do të punoni ngushtë me dizajnerët tanë dhe zhvilluesit e backend-it për të krijuar aplikacione uebi të shkallëzueshme që përdoren nga mijëra përdorues në Nordik.',
    'jobs.react_req': 'Së paku 5 vjet përvojë me JavaScript/TypeScript;Ekspertizë e thellë në React dhe ekosistemin e tij (Redux, Zustand, React Query);Përvojë në udhëheqjen e diskutimeve teknike dhe mentorimin e zhvilluesve të rinj;Fokus i fortë në optimizimin e performancës.',
    'jobs.react_ben': 'Pagë konkurruese;Harduer modern;Opsione për punë në distancë;Trajnim i vazhdueshëm.',
    'jobs.net_desc_short': 'A jeni ekspert në C# dhe zgjidhje moderne cloud? Ndihmoni klientët tanë të ndërtojnë sisteme të shkallëzueshme.',
    'jobs.net_desc_full': 'Ne po kërkojmë një zhvillues Fullstack .NET i cili lulëzon në një mjedis me ritëm të lartë dhe ekselencë teknike. Ju do të ndërtoni zgjidhje të bazuara në cloud (Azure/AWS) dhe do të siguroni që sistemet tona backend të jenë të forta dhe të sigurta. Roli juaj përfshin gjithçka nga dizajni i bazës së të dhënave deri te zhvillimi i API-ve dhe integrimet.',
    'jobs.net_req': 'Përvojë solide në .NET Core dhe C#;Njohuri për bazat e të dhënave moderne (SQL & NoSQL);Përvojë me platformat cloud dhe CI/CD pipelines;Aftësi për të shkruar kod të pastër dhe të testueshëm.',
    'jobs.net_ben': 'Mbështetje për certifikim;Shtesa për mirëqenie;Ambient frymëzues zyre;Rrugë e qartë karriere.',
    'jobs.hr_desc_short': 'Ne po kërkojmë dikë që kupton si kulturën nordike të punës ashtu edhe tregun lokal të talenteve.',
    'jobs.hr_desc_full': 'Si Specialist i BNJ me ne, ju luani një rol kyç në ndërtimin e ekipeve tona në Kosovë. Ju veproni si një lidhje midis klientëve tanë nordikë dhe talenteve tona lokale. Ju do të jeni përgjegjës për të gjithë procesin e rregullimit, nga kërkimi deri te përfshirja dhe kujdesi për personelin.',
    'jobs.hr_req': 'Përvojë në rekrutim teknologjik;Kuptimi i kulturës nordike të punës;Aftësi të shkëlqyera komunikimi në anglisht;Personalitet i motivuar dhe i pavarur.',
    'jobs.hr_ben': 'Zhvillim personal;Networking me kompani ndërkombëtare;Orar fleksibël pune;Një rol me ndikim të lartë.',
    'careers.send_spontaneous': 'DËRGO APLIKIM SPONTAN',
    'value.bullet1_val1': 'Rekrutim etik i studentëve top',
    'value.bullet2_val1': 'Përfitimet lider në treg',
    'value.bullet3_val1': 'Trajnim i vazhdueshëm dhe mentorim',
    'value.bullet4_val1': 'Një kulturë e ndërtuar mbi respektin dhe besimin',
    'value.bullet1_val2': 'Rrjedha e punës e fokusuar në rezultate',
    'value.bullet2_val2': 'Orari fleksibël i punës',
    'value.bullet3_val2': 'Infrastruktura Remote-first',
    'value.bullet4_val2': 'Cilësi e lartë në çdo dërgesë',
    'value.bullet1_val3': 'Konfigurimi i ekipeve sipas nevojës',
    'value.bullet2_val3': 'Menaxherë llogarie të dedikuar',
    'value.bullet3_val3': 'Integrim i qetë në organizatën tuaj',
    'value.bullet4_val3': 'Zgjidhje të shkallëzueshme nga 1-50 persona',
    'reviews.title': 'ÇFARË THONË KLIENTËT TANË',
    'reviews.subtitle': 'Recensionet e publikuara',
    'reviews.form_title': 'Lini recensionin tuaj',
    'reviews.form_desc': 'Ne e vlerësojmë feedbackun tuaj për t\'u përmirësuar vazhdimisht.',
    'reviews.label_rating': 'VLERËSIMI',
    'reviews.label_name': 'EMRI',
    'reviews.label_comment': 'KOMENTI',
    'reviews.btn_submit': 'DËRGO',
    'reviews.success_title': 'Faleminderit për feedbackun tuaj!',
    'reviews.success_desc': 'Mesazhi juaj i është dërguar ekipit tonë.',
    'cookies.title': 'Ne e vlerësojmë privatësinë tuaj',
    'cookies.desc': 'Ne përdorim cookie për të përmirësuar përvojën tuaj, për të analizuar trafikun dhe për të personalizuar përmbajtjen. Duke vazhduar, ju pranoni përdorimin tonë të cookie-ve.',
    'cookies.accept': 'Prano të gjitha',
    'cookies.decline': 'Refuzo',
    'cookies.policy': 'Politika e privatësisë',
    'cookies.settings': 'Cilësimet',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('sv');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['sv']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};